samples_dir:
    "2018": ../eos/hww/Dec20_hww_2018
    "2017": ../eos/hww/Dec20_hww_2017
    "2016": ../eos/hww/Dec20_hww_2016
    "2016APV": ../eos/hww/Dec20_hww_2016APV

years:
    - "2018"
    - "2017"
    - "2016"
    - "2016APV"

channels:
    - ele
    - mu

presel:
    ele:
        msoftdrop: (fj_mass>40)
        THWW: (THWW>0.75)
    mu:
        msoftdrop: (fj_mass>40)
        THWW: (THWW>0.75)

samples:
    - ggF
    - VBF
    - ttH
    - WH
    - ZH
    - Fake
    - QCD
    - SingleTop
    - Diboson
    - EWKvjets
    - DYJets
    - WZQQ
    - TTbar
    - WJetsLNu
    - Data

THWW_path: ../ParT_Finetuned/v35_30/model.onnx

outdir: "hists/v2/"
